### ISSUE TITLE
Library doesn't work in Android 9.0

### ISSUE THREAD

**Issue by moisesvs** [CuriousNikhil/AsynKio#3]
When I am trying run the library in Android 9.0. Library doesn't work. Library return me the following error:

W/stine.nekoslif: Accessing hidden field Ljava/net/URL;->host:Ljava/lang/String; (dark greylist, reflection)

I searched the error in stackoverflow with the following solution:

https://stackoverflow.com/questions/53827256/android-9-0-java-net-url

**Comment by CuriousNikhil** [comment]
Hi @moisesvs 
I'm on it, thanks.
