### ISSUE TITLE
Feature Support for SSLContext

### ISSUE THREAD

**Issue by Hakky54** [CuriousNikhil/AsynKio#7]
Hi,

Thank you for this awesome http client. I noticed that there is no option to pass an instance of SSLContext within the requests. It would be great to have that option as well for https requests which will enable me and other developers to use a custom list of trusted certificates or even provide a custom client certificate as well for mutual authentication. Would that be possible?

Kinds regards,
Hakan

**Comment by CuriousNikhil** [comment]
@Hakky54 thanks for stopping by. It's been a long time I've not worked on this library. But you can absolutely fork /clone it and tweak it as per your needs or maybe you can raise a pull request. 
It'll be appreciated. Thanks. 😄

**Comment by Hakky54** [comment]
Sounds fun and thank you for actively promoting users to sent pull requests! I forked it and did some changes and also created a pull request, please have a look here: https://github.com/CuriousNikhil/AsynKio/pull/8

**Comment by CuriousNikhil** [comment]
Pull request merged. 
Closing the issue.
